/**
 * Service Worker Registration Module
 * 
 * Registers the service worker generated by vite-plugin-pwa and handles updates.
 */

export interface ServiceWorkerConfig {
  onUpdate?: (registration: ServiceWorkerRegistration) => void
  onSuccess?: (registration: ServiceWorkerRegistration) => void
}

/**
 * Register service worker with update detection
 */
export function registerServiceWorker(config?: ServiceWorkerConfig): void {
  if (!('serviceWorker' in navigator)) {
    console.warn('Service workers are not supported in this browser')
    return
  }

  window.addEventListener('load', () => {
    registerSW(config)
  })
}

/**
 * Internal registration function
 */
async function registerSW(config?: ServiceWorkerConfig): Promise<void> {
  try {
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
    })

    console.log('Service Worker registered successfully:', registration.scope)

    // Check for updates
    registration.addEventListener('updatefound', () => {
      const newWorker = registration.installing
      if (!newWorker) return

      newWorker.addEventListener('statechange', () => {
        if (newWorker.state === 'installed') {
          if (navigator.serviceWorker.controller) {
            // New content is available, notify user
            console.log('New content is available. Please refresh.')
            config?.onUpdate?.(registration)
            showUpdateNotification()
          } else {
            // Content is cached for offline use
            console.log('Content is cached for offline use.')
            config?.onSuccess?.(registration)
          }
        }
      })
    })

    // Handle controller change (when new SW takes over)
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      console.log('New service worker is controlling the page')
      // Optionally auto-reload or notify user
    })
  } catch (error) {
    console.error('Service Worker registration failed:', error)
  }
}

/**
 * Show update notification to user
 */
function showUpdateNotification(): void {
  // Create a simple notification element
  const notification = document.createElement('div')
  notification.style.cssText = `
    position: fixed;
    bottom: 20px;
    right: 20px;
    background: #15803d;
    color: white;
    padding: 16px 24px;
    border-radius: 8px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    z-index: 9999;
    font-family: system-ui, -apple-system, sans-serif;
    cursor: pointer;
    animation: slideIn 0.3s ease-out;
  `
  notification.innerHTML = `
    <div style="font-weight: 600; margin-bottom: 4px;">নতুন আপডেট available</div>
    <div style="font-size: 14px; opacity: 0.9;">নতুন ফিচার পেতে রিফ্রেশ করুন</div>
  `

  notification.addEventListener('click', () => {
    window.location.reload()
  })

  document.body.appendChild(notification)

  // Auto-remove after 10 seconds
  setTimeout(() => {
    notification.style.animation = 'slideOut 0.3s ease-out'
    setTimeout(() => notification.remove(), 300)
  }, 10000)
}

/**
 * Unregister service worker (for development/debugging)
 */
export async function unregisterServiceWorker(): Promise<void> {
  if (!('serviceWorker' in navigator)) return

  const registration = await navigator.serviceWorker.ready
  await registration.unregister()
  console.log('Service Worker unregistered')
}

/**
 * Check if service worker is registered and active
 */
export function isServiceWorkerActive(): boolean {
  return 'serviceWorker' in navigator && !!navigator.serviceWorker.controller
}

/**
 * Send message to service worker
 */
export function sendMessageToSW(message: unknown): Promise<unknown> {
  return new Promise((resolve, reject) => {
    if (!navigator.serviceWorker.controller) {
      reject(new Error('No service worker controller'))
      return
    }

    navigator.serviceWorker.controller.postMessage(message)
    
    navigator.serviceWorker.addEventListener('message', function handler(event) {
      navigator.serviceWorker.removeEventListener('message', handler)
      resolve(event.data)
    })
  })
}
